
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class quan_Ly_Thong_Tin extends javax.swing.JFrame {

    /**
     * Creates new form quan_Ly_Thong_Tin
     * 
     */
    public quan_Ly_Thong_Tin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        txtAccountName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btncapnhat = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableAccount = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quản Lý Thông Tin Tài Khoản");

        jLabel2.setText("Số Tài KHoản");

        jLabel3.setText("Tên Khách Hàng");

        jLabel4.setText("Địa Chỉ");

        jLabel5.setText("Số Tiền");

        btncapnhat.setText("Cập Nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        jtableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Tài Khoản", "Tên Khách Hàng", "Địa Chỉ", "Số Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableAccount);

        jLabel6.setText("Tổng Tiền ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btncapnhat)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnxoa)
                                        .addGap(60, 60, 60)
                                        .addComponent(btnthoat))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAccount)
                                        .addComponent(txtAccountName)
                                        .addComponent(txtAddress)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncapnhat)
                    .addComponent(btnxoa)
                    .addComponent(btnthoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        
         try  
          { 
                if("".equals(txtAccount.getText()) || 
                        "".equals(txtAccountName.getText()) || "".equals(txtAddress.getText()) ) 
                { 
                    throw new Exception("Vui lòng nhập đầy đủ thông tin!"); 
                } 
                int row = GetAccountRow(txtAccount.getText()); 
                //tao doi tuong Account temp  
                Account temp = new 
                Account(txtAccount.getText(),txtAccountName.getText(), 
                txtAddress.getText(),Double.parseDouble(txtAmount.getText()) ); 
                DefaultTableModel model = (DefaultTableModel) 
                jtableAccount.getModel(); //lay model mac dinh tu jtable 
                if(row == -1)  //TH insert 
                {                      
                    int STT = 1;  
                    if(model.getRowCount()> 0) 
                    {  STT = (int) model.getValueAt(model.getRowCount()-1, 0); 
                       STT++; 
                    } 
                                       
                    model.addRow(new Object[]{ STT , temp.AccountNo, 
                     temp.AccountName, temp.Address , temp.Amount});  
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE); 
                } 
                else  //TH update  
                {                  
                     model.setValueAt(temp.AccountName, row, 2); 
                     model.setValueAt(temp.Address, row, 3); 
                     model.setValueAt(temp.Amount, row, 4);     
                    JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE); 
                }
                float Tong=0;
                for(int i= 0;i < model.getRowCount();i++)
                {
                    float a =(float)jtableAccount.getModel().getValueAt(1,4);
                    Tong += a;
                }
                String tongs = Float.toString(Tong);
                txtTong.setText(tongs);
          } 
          catch(Exception ex) 
          { 
             JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE); 
          } 
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try  
        { 
                int row = GetAccountRow(txtAccount.getText());  
                if(row == -1)  //TH insert 
                     { 
                    throw new Exception("Không tìm thấy số tài khoản cần xóa!"); 
                } 
                else  //TH remove  
                { 
                    //goi confirm message  
                      int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?", "Cảnh báo", JOptionPane.YES_NO_OPTION); 
                      // 0=yes, 1=no, 2=cancel 
                      DefaultTableModel model = (DefaultTableModel)jtableAccount.getModel();
                      if(input == 0)  //th yes 
                      {   
                           model.removeRow(row);                     
                           JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);                   
                      } 
                      for(int i=0;i< model.getRowCount();i++)
                      {
                          model.setValueAt(i+1,i,0);
                      }
                } 
          } 
          catch(Exception ex) 
          { 
             JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE); 
          }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jtableAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableAccountMouseClicked
        // TODO add your handling code here:
        try{
            DefaultTableModel model=(DefaultTableModel)jtableAccount.getModel();
             int row = jtableAccount.getSelectedRow();  
             Account temp = new Account(model.getValueAt(row, 
             1).toString(),model.getValueAt(row, 2).toString(), model.getValueAt(row, 
             3).toString(), Double.parseDouble(model.getValueAt(row, 4).toString()));   
              SetAccount(temp); 
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jtableAccountMouseClicked

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quan_Ly_Thong_Tin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quan_Ly_Thong_Tin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quan_Ly_Thong_Tin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quan_Ly_Thong_Tin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quan_Ly_Thong_Tin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableAccount;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables

    private int GetAccountRow(String accountNo) {
      DefaultTableModel model = (DefaultTableModel)jtableAccount.getModel(); 
        for (int i = 0;i< model.getRowCount(); i++)  
        { 
               if(model.getValueAt(i, 1).toString().equals(accountNo.trim())) 
                    return i;             
        } 
        return -1; //To change body of generated methods, choose Tools | Templates.
    }

    private void SetAccount(Account temp) {
         txtAccount.setText(temp.AccountNo); 
         txtAccountName.setText(temp.AccountName); 
         txtAddress.setText(temp.Address); 
         txtAmount.setText(String.valueOf(temp.Amount));  //To change body of generated methods, choose Tools | Templates.
    }
    
}
